#=======================================================
#
#                  SkyKnock DEV.
#             https://t.me/skyknockdev
#
#========================================================
banworld:
  - world
unbanwolrd:
  - world
deleteworld:
  - world

blockbreak: "§cВам запрещено ломать данный блок!"
blockplase: "§cВам запрещено ставить данный блок!"
blockdelete: "§aВсе ненужные блоки успешно удалены!"

delay: 86400

messages:
  add: "§aВы успешно запретили блок %name%"
  rem: "§aВы успешно убрали защиту с блока %name%"
  time: "§aВы успешно установили время очистки на %time% сек."
  perm: "§cУ вас недостаточно прав для этого"